# import pandas as pd

# 原则列表统一小写
pri_list = ['actor observer asymmetry', 'defensive attribution hypothesis', 'effort justification', 'egocentric bias', 'false consensus effect', 'forer effect', 'fundamental attribution error', 'hard-easy effect', 'illusion of control', 'illusory superiority', 'optimism bias', 'overconfidence effect', 'risk compensation', 'self-serving bias', 'social desirability bias', 'third-person effect', 'decoy effect', 'reactance', 'social comparison bias', 'status quo bias', 'backfire effect', 'endowment effect', 'loss aversion', 'pseudocertainty effect', 'sunk cost fallacy', 'zero-risk bias', 'hyperbolic discounting', 'identifiable victim effect', 'ambiguity bias', 'belief bias', 'information bias', 'less-is-better effect', 'authority bias', 'automation bias', 'bandwagon effect', 'group attribution error', 'just-world hypothesis', 'stereotyping', 'ultimate attribution error', 'halo effect', 'in-group bias', 'out-group homogeneity bias', 'positivity effect', 'reactive devaluation', 'hindsight bias', 'impact bias', 'outcome bias', 'pessimism bias', 'planning fallacy', 'projection bias', 'restraint bias', 'self-consistency bias', 'denomination effect', 'mental accounting', 'normalcy bias', 'subadditivity effect', 'survivorship bias', 'zero-sum bias', 'anthropomorphism', 'illusion of validity', 'illusory correlation', 'curse of knowledge', 'illusion of asymmetric insight', 'illusion of transparency', 'spotlight effect', 'negativity bias', 'choice-supportive bias', 'confirmation bias', 'continued influence effect', 'expectation bias', 'observer effect', 'observer-expectancy effect', 'ostrich effect', 'bias blind spot', 'naive cynicism',
            'naive realism', 'attentional bias', 'availability heuristic', 'base rate fallacy', 'context effect', 'empathy gap', 'illusory truth effect', 'mere exposure effect', 'mood-congruent memory bias', 'omission bias', 'anchoring', 'conservatism', 'contrast effect', 'distinction bias', 'focusing effect', 'framing effect', 'fading affect bias', 'implicit association', 'implicit stereotypes', 'false memory', 'misattribution of memory', 'source confusion', 'misinformation effect', 'peak-end rule', 'delayed reciprocity', 'asymmetrical investment', 'survival imperative', 'aversion response', 'narrative self', 'hedonic adaptation', 'self-determination theory', 'pleasure principle & reality principle', 'search for meaning', 'moral licensing effect', 'choice overload', 'kin selection & inclusive fitness', 'asymmetrical parental investment', 'formation of dominance hierarchies', 'territoriality', 'mating strategies', 'jealousy', 'paternity uncertainty', 'groupthink', 'bystander effect', 'social facilitation', 'diffusion of responsibility', 'decision fatigue', 'awe', 'mortality salience & legacy drive', 'flow principle', 'gratitude mechanism', 'post-traumatic growth', 'skin hunger & the law of touch', 'self-handicapping paradox', 'the allure of the forbidden', 'sadistic pleasure', 'the utility principle of self-deception', 'play impulse principle', 'attribution theory', 'social comparison theory', 'self-perception theory', 'terror management theory', 'cognitive dissonance theory', 'psychological reactance theory', 'social learning theory', 'conformity', 'obedience to authority', 'social identity theory', 'bystander effect', 'reciprocity principle']

situation_P = ['Situation is potentially enjoyable.', 'Situation is complex.', 'A job needs to be done.', 'Someone is trying to impress P.', 'Someone is trying to convince P of something.', 'P is counted on to do something.', 'Talking is permitted.', 'Talking is expected or demanded.', 'P is being asked for something.', 'Someone needs help.', 'Minor details are important.', 'Situation evokes values concerning lifestyles or politics.', 'Affords an opportunity to demonstrate intellectual capacity. (e.g., an intellectual discussion, a complex problem needs to be solved)', 'Situation is uncertain.', 'Another person (present or discussed) is under threat.', 'P is being criticized, directly or indirectly.', 'Someone is attempting to dominate or boss P.', 'Situation is playful.', 'Introspection is possible. (e.g., the atmosphere allows or encourages reflection upon deeply personal issues)', 'Things are happening quickly. (Low placement implies things are happening slowly.)', 'Someone (present or discussed) is unhappy or suffering.', 'A reassuring other person is present.', 'P is being blamed for something.', 'A decision needs to be made.', 'Rational thinking is called for.', 'Situation calls for self-restraint.', 'Situation involves competition.', 'Affords an opportunity for P to do things that might make P liked or accepted.', 'Others are present who need or desire reassurance.', 'Situation entails frustration. (e.g., a goal is blocked)', 'Physical attractiveness of P is relevant.', 'It is important for P to make a good impression.', 'Situation would make some people tense and upset.', 'Situation includes one or more small annoyances.', 'Situation might evoke warmth or compassion.', 'A person or activity could be undermined or sabotaged.', 'It is possible for P to deceive someone.', 'Someone else in this situation (other than P) might be deceitful.', 'Situation may cause feelings of hostility.', 'People are disagreeing about something.', 'Affords an opportunity to express unusual ideas or points of view.', 'Situation contains physical threats.', 'Situation contains emotional threats.', 'Situation raises moral or ethical issues. (e.g., a moral dilemma is present; a discussion of morality)', 'A quick decision or quick action is called for.', 'Situation allows a free range of emotional expression.', 'Others present might have conflicting or hidden motives.', 'Situation entails or could entail stress or trauma.', 'Affords an opportunity to ruminate, daydream or fantasize.',
               'Situation has potential to arouse guilt in P.', 'Close personal relationships are present or have the potential to develop.', 'Someone other than P is counted on to do something.', 'Situation includes intellectual or cognitive stimuli. (e.g., books, lectures, intellectual conversation)', 'Assertiveness is required to accomplish a goal.', 'Situation includes potential for immediate gratification of desires. (e.g., food, shopping, sexual opportunities)', 'Social interaction is possible.', 'Situation is humorous or potentially humorous. (if one finds that sort of thing funny)', 'P is the focus of attention.', 'Situation includes sensuous stimuli. (e.g., touch, taste, smell, physical contact)', 'Situation is relevant to bodily health of P. (e.g., possibility of illness; a medical visit)', 'Success in this situation requires self-insight.', 'P controls resources needed by others.', 'Others present a wide range of interpersonal cues. (e.g., body language, tone of voice, social signals)', 'Situation includes behavioral limits. (e.g., rules or social norms that might or might not be challenged)', 'Situation includes aesthetic stimuli. (e.g., art, music, drama, beauty)', 'Situation is potentially anxiety-inducing.', 'Situation makes demands on P. (either explicitly or implicitly)', 'Affords an opportunity to express or demonstrate ambition.', 'Situation might make P feel inadequate.', 'Situation includes stimuli that could be construed sexually.', 'Situational demands are rapidly shifting.', 'P is being abused or victimized.', 'Members of the opposite sex are present.', 'Potential romantic partners for P are present.', 'Situation has potential to arouse competing motivations.', 'Situation is basically simple and clear-cut.', 'Affords an opportunity to express charm.', 'Situation involves social comparison.', 'Situation raises issues of power. (for P or others present)', 'Affords an opportunity to express masculinity.', 'Others may need or are requesting advice from P.', 'Independence or autonomy of P is questioned or threatened.', 'Situation is potentially emotionally arousing.', 'Affords an opportunity for demonstrating verbal fluency. (e.g., a debate, a monologue, an active conversation)', 'People who are present occupy different social roles or levels of status.', 'P is being pressured to conform to the actions of others.', 'Success requires cooperation.', 'P is being complimented or praised.', 'Affords an opportunity to express femininity.']

Situation = ['Situation is potentially enjoyable.', 'Situation is complex.', 'A job needs to be done.', 'Someone is trying to impress someone.', 'Someone is trying to convince someone of something.', 'Someone is counted on to do something.', 'Talking is permitted.', 'Talking is expected or demanded.', 'Someone is being asked for something.', 'Someone needs help.', 'Minor details are important.', 'Situation evokes values concerning lifestyles or politics.', 'Affords an opportunity to demonstrate intellectual capacity. (e.g., an intellectual discussion, a complex problem needs to be solved)', 'Situation is uncertain.', 'Another person (present or discussed) is under threat.', 'Someone is being criticized, directly or indirectly.', 'Someone is attempting to dominate or boss someone.', 'Situation is playful.', 'Introspection is possible. (e.g., the atmosphere allows or encourages reflection upon deeply personal issues)', 'Things are happening quickly. (Low placement implies things are happening slowly.)', 'Someone (present or discussed) is unhappy or suffering.', 'A reassuring other person is present.', 'Someone is being blamed for something.', 'A decision needs to be made.', 'Rational thinking is called for.', 'Situation calls for self-restraint.', 'Situation involves competition.', 'Affords an opportunity for someone to do things that might make someone liked or accepted.', 'Others are present who need or desire reassurance.', 'Situation entails frustration. (e.g., a goal is blocked)', 'Physical attractiveness of someone is relevant.', 'It is important for someone to make a good impression.', 'Situation would make some people tense and upset.', 'Situation includes one or more small annoyances.', 'Situation might evoke warmth or compassion.', 'A person or activity could be undermined or sabotaged.', 'It is possible for someone to deceive someone.', 'Someone else in this situation (other than someone) might be deceitful.', 'Situation may cause feelings of hostility.', 'People are disagreeing about something.', 'Affords an opportunity to express unusual ideas or points of view.', 'Situation contains physical threats.', 'Situation contains emotional threats.', 'Situation raises moral or ethical issues. (e.g., a moral dilemma is present; a discussion of morality)', 'A quick decision or quick action is called for.', 'Situation allows a free range of emotional expression.', 'Others present might have conflicting or hidden motives.', 'Situation entails or could entail stress or trauma.', 'Affords an opportunity to ruminate, daydream or fantasize.',
             'Situation has potential to arouse guilt in someone.', 'Close personal relationships are present or have the potential to develop.', 'Someone other than someone is counted on to do something.', 'Situation includes intellectual or cognitive stimuli. (e.g., books, lectures, intellectual conversation)', 'Assertiveness is required to accomplish a goal.', 'Situation includes potential for immediate gratification of desires. (e.g., food, shopping, sexual opportunities)', 'Social interaction is possible.', 'Situation is humorous or potentially humorous. (if one finds that sort of thing funny)', 'Someone is the focus of attention.', 'Situation includes sensuous stimuli. (e.g., touch, taste, smell, physical contact)', 'Situation is relevant to bodily health of someone. (e.g., possibility of illness; a medical visit)', 'Success in this situation requires self-insight.', 'Someone controls resources needed by others.', 'Others present a wide range of interpersonal cues. (e.g., body language, tone of voice, social signals)', 'Situation includes behavioral limits. (e.g., rules or social norms that might or might not be challenged)', 'Situation includes aesthetic stimuli. (e.g., art, music, drama, beauty)', 'Situation is potentially anxiety-inducing.', 'Situation makes demands on someone. (either explicitly or implicitly)', 'Affords an opportunity to express or demonstrate ambition.', 'Situation might make someone feel inadequate.', 'Situation includes stimuli that could be construed sexually.', 'Situational demands are rapidly shifting.', 'Someone is being abused or victimized.', 'Members of the opposite sex are present.', 'Potential romantic partners for someone are present.', 'Situation has potential to arouse competing motivations.', 'Situation is basically simple and clear-cut.', 'Affords an opportunity to express charm.', 'Situation involves social comparison.', 'Situation raises issues of power. (for someone or others present)', 'Affords an opportunity to express masculinity.', 'Others may need or are requesting advice from someone.', 'Independence or autonomy of someone is questioned or threatened.', 'Situation is potentially emotionally arousing.', 'Affords an opportunity for demonstrating verbal fluency. (e.g., a debate, a monologue, an active conversation)', 'People who are present occupy different social roles or levels of status.', 'Someone is being pressured to conform to the actions of others.', 'Success requires cooperation.', 'Someone is being complimented or praised.', 'Affords an opportunity to express femininity.']


excel_file = './Dataset/principle.xlsx'


# def ptoe():
#     df = pd.DataFrame(pri_list)
#     df.to_excel(excel_file, index=False, header=False)
#     return


# def etop():
#     df = pd.read_excel(excel_file, header=None)
#     pri_list = df[0].tolist()
#     print(pri_list)
#     return


# if __name__ == '__main__':
# ptoe()
# etop()
# print(len(pri_list))
# print(f"Total items in the list: {len(situation)}")
# print(situation_domain)
# print(situation_domain)
# print(len(Situation))
